version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - mc-jones
    reviewers:
      - artsy/platform-engineers
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - mc-jones
    reviewers:
      - artsy/platform-engineers