language: ruby
sudo: false
cache: bundler
rvm:
- 2.6.3
branches:
  except:
    - master
    - archived_octopress

install:
  - gem install bundler
  - bundle install --with=distribution
  - git config --global user.email "deploys@artsy.net"
  - git config --global user.name "GH Pages Deploy Bot"


script:
  - rake build
  - '[ -z $DANGER_GITHUB_API_TOKEN ] && echo "Skipping Danger for External Contributor" || bundle exec danger'

after_success: rake deploy:travis
